cc_binary(
    name = "hello",
    srcs = ["hello.c"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "hi",
    srcs = ["hi.c"],
    hdrs = ["hi.h"],
    #    includes = [".",],
    visibility = ["//visibility:public"],
)
